### ISSUE TITLE
Unhandled exception has occurred in your application. The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

### ISSUE THREAD

**Issue by ronamregins** [fireshaper/Omnibus#10]
**Describe the bug**
Unhandled exception has occurred in your application. The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

**To Reproduce**
1. Open Omnibus v1.4.8.1
2. Follow setup instructions. Used Microsoft Edge as Browser, also tried with Mozilla Firefox but same error
3. Search for comic. Click download.

**Expected behavior**
Download should have started.

**Screenshots**
![Screenshot 2020-10-14 065900](https://user-images.githubusercontent.com/72838060/95924801-dc08ba80-0dea-11eb-996b-b0ef63d41a2d.png)
![image](https://user-images.githubusercontent.com/72838060/95924924-212cec80-0deb-11eb-8e08-ba4c4bcb5654.png)
![image](https://user-images.githubusercontent.com/72838060/95924969-3e61bb00-0deb-11eb-8c0b-e2cb65aad544.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Single Language
 - Version 2004 OS Build 19041.58 

**Additional context**

**Comment by fireshaper** [comment]
I see two things it might be. It's either that I'm not handling the Yen sign correctly as the file separator or there's a space in your _cfduid: "[...]59b 160[...]". Can you make sure that there's not a space in the cookie?

**Comment by ronamregins** [comment]
Alright, I'll check it out. Update you tomorrow

**Comment by hbllq** [comment]
I have the same bug. My folder structure is the usual C:\users\username\documents format and I have checked that my cfduid has no spaces so I don't think it's that. If I press the more details button I get this: 

"at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
  at System.Convert.FromBase64String(String s)
   at Omnibus.Form1.<btnDownload_ClickAsync>d__28.MoveNext() in C:\Users\Rory\source\repos\Omnibus\Comic Search\Form1.cs:regel 274"

**Comment by fireshaper** [comment]
The problem was that getcomics.info stopped encrypting their MEGA links. I've got a check in there now to see if the link is an encrypted string or not, then it will give you the right one. New release is available: https://github.com/fireshaper/Omnibus/tree/1.4.8.2

**Comment by ronamregins** [comment]
Issue resolved for me with the 1.4.8.2 update. Will close this issue. Thanks!
