### ISSUE TITLE
1.4.8.2 Unable to perform search

### ISSUE THREAD

**Issue by abracacarba** [fireshaper/Omnibus#11]
I am suddenly unable to do a search for anything using 1.4.8.2. It had been working perfect prior to this morning.

When I open the program, and press search, I get the message:

**"No cookies in settings. Setup your cookies and try again"**

as though I did not go through the initial setup. Those settings are filled in however, and have been since I last used it successfully yesterday.

I've tried setting it up again using both Chrome and Edge on two separate computers and I get the same result each time.

Looking at the log, I see:

(11-04-20 10:41:08) - Searching for https://getcomics.info/page/1/?s= failed.
(11-04-20 10:41:08) - System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.GetResponse()
   at Omnibus.Form1.searchComics(String function) in C:\Users\Rory\source\repos\Omnibus\Comic Search\Form1.cs:line 804
(11-04-20 10:41:10) - Searched for new comics.

**Comment by Raimilover76** [comment]
I have this same exact issue

**Comment by fireshaper** [comment]
It looks like they are requiring the cf_clearance cookie again. I'm going to try to put in some more logic to catch this in case it changes in the future.

**Comment by Raimilover76** [comment]
Ok, just to be clear we're supposed to copy the value part?

**Comment by Raimilover76** [comment]
I copied value from the cf_clearance cookie and it didn't work

**Comment by fireshaper** [comment]
I'm working on the issue, I'll have to release a new version.

**Comment by fireshaper** [comment]
Release 1.4.8.3 resolves the issue. Make sure you fill in all cookies again in the settings.

https://github.com/fireshaper/Omnibus/releases/tag/1.4.8.3

**Comment by Raimilover76** [comment]
Thanks, its working now
