### ISSUE TITLE
Error when starting download [BUG]

### ISSUE THREAD

**Issue by RiggityRow** [fireshaper/Omnibus#12]
Bug for 1.4.8.3

Error message when trying to download that says "Invalid length for a Base-64 char array or string"

**Comment by iplayminecraf** [comment]
Yeah this was happening to me recently too. I didn't report it as I thought I messed it up. Some times it changes the message to URI not found but verifying the mega link does nothing.

**Comment by abracacarba** [comment]
Can confirm. Same issues for me since at least 1/20.

**Comment by redredkrovy** [comment]
Just came across your program and installed it.  Having the same issue as above.

**Comment by ghost** [comment]
I am also having this issue. [Here is a paste of the output.](https://bin.snopyta.org/?9e555bbcf2b58ab5#9eWYpnGfGeHCDHuykAGbxLLCbSfADRGRagGMzrNurTNw)

**Comment by yorai1212** [comment]
Same issue!

**Comment by fireshaper** [comment]
Release 1.4.8.4 should resolve this now.
