### ISSUE TITLE
"The connection was closed unexpectedly" when downloading

### ISSUE THREAD

**Issue by ghost** [fireshaper/Omnibus#13]
[Here is a paste of the error output](https://bin.snopyta.org/?7868929a9859637b#RVfHSywytX3YN78KWEEuSxiHSCxonGXD2f9z5Fca5yv).

I'm on Windows 10 (2004), 64-bit with Omnibus 1.4.8.4.

**Comment by fireshaper** [comment]
What comic were you downloading when you got this error?
