### ISSUE TITLE
[BUG] No mediafire button, when mediafire link exists

### ISSUE THREAD

**Issue by ducky0518** [fireshaper/Omnibus#15]
**Describe the bug**
Clicking on "download" on specific comments where there are mediafire links, but not a mediafire "button" shouldn't cause an issue.

**To Reproduce**
1. Find "Rust Vol. 0 - 4" comic
2. Click on 'Download comic'
3. Error occurs
4. Go to manual page - https://getcomics.info/other-comics/rust-vol-0-3-tpb-2016-2017/ and see that mediafire link exists

**Expected behavior**
Comic downloads correctly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
  - Version 1802

**Additional context**
Also, after the error comes up, the application tells you to go to the page manually, which is fine, but then an exception occurs, which shouldn't happen.

**Comment by fireshaper** [comment]
No longer using MediaFire for downloads. Version 1.5 now uses the Direct Link.
