### ISSUE TITLE
Download location not saving (likely not an Omnibus issue)

### ISSUE THREAD

**Issue by vmcosco** [fireshaper/Omnibus#20]
Sorry for opening a ticket for something that may not be an Omnibus issue.  I wasn't sure how else to get it resolved.

I am running Omnibus v1.5 (nice update btw) on Ubuntu using Wine.  If you aren't familiar with Wine it is a application for Linux that allows you to run Windows programs.  I have Omnibus working great but am having one issue:

I am able to set my download location in settings and it works during that session.  When I close Omnibus and reopen, the download location has reverted back to the default (install) location.

I understand this may very well be a Wine issue, but I am wondering where in the code the download location gets saved?  Maybe it is not able save for some reason so when I exit, it reverts back.  I checked in omnibus.exe.config but seems to be a reference and not the actual value.

Thanks, and again, sorry for opening the issue.

 - OS: Ubuntu 20.04

**Comment by fireshaper** [comment]
Sorry about that. Looks like there was some remnants of old code in there that wasn't affecting Windows users, but did affect Wine. I released a new version with a fix (1.5.0.1).

**Comment by fireshaper** [comment]
Since there has been no update on this in a few days I'm going to close the issue out.
