### ISSUE TITLE
Search requires button click and doesn't respond to {Enter}

### ISSUE THREAD

**Issue by wolfkin** [fireshaper/Omnibus#4]
v1.4.4 - Win10

1. type in a query into search box
2. hit {Enter}

response: 
>error tone

expected response:
>same as clicking the "Search" button to the right of the search box

**Comment by fireshaper** [comment]
Resolved in https://github.com/fireshaper/Omnibus/commit/4fc24db63c55d6dbf4981af757c7aac628287895. Version 1.4.5 added to Release.

https://github.com/fireshaper/Omnibus/releases/tag/1.4.5
