### ISSUE TITLE
Unable to extract Id and Key from the uri

### ISSUE THREAD

**Issue by theotherp** [fireshaper/Omnibus#5]
Thanks for the great tool. I was about to code something similar and then found this by accident.

I get the following error:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Invalid uri. Unable to extract Id and Key from the uri https://getcomics.info/run.php-urls/aHR0cHM6Ly9tZWdhLm56LyMhS2dWa2pRS1MhaktFWXprX1hUU1dDX3Z6emhnb0VuTWZSbEFNaGlsakNRR2pqTnZ5enhGMA==
   at CG.Web.MegaApiClient.MegaApiClient.GetPartsFromUri(Uri uri, String& id, Byte[]& iv, Byte[]& metaMac, Byte[]& key)
   at CG.Web.MegaApiClient.MegaApiClient.Download(Uri uri, Nullable`1 cancellationToken)
   at CG.Web.MegaApiClient.MegaApiClient.<>c__DisplayClass73_0.<DownloadFileAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Omnibus.Form1.<DownloadComic>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

I searched for "Something Is Killing the Children" and tried to download issue #1.

Thanks!

**Comment by fireshaper** [comment]
I have been notified of this issue and at this moment I only have a workaround:

Close Omnibus, open a browser and click on the MEGA button for any comic on getcomics.info
Then open Omnibus again and download something that didn't work

I think there's some cookie/session/something being set on the machine that is causing this issue.

**Comment by theotherp** [comment]
Doesn't work :-(

**Comment by fireshaper** [comment]
Try the new release https://github.com/fireshaper/Omnibus/releases/tag/1.4.6.2

**Comment by theotherp** [comment]
Nope, sorry.

**Comment by fireshaper** [comment]
Can you right-click on the comic you are trying to download and choose "Verify MEGA link" and send me a screenshot of that?

**Comment by theotherp** [comment]
I only have the option to "Find more like this"...

**Comment by fireshaper** [comment]
You aren't using the newest release then. I sent you a link direct to it.

**Comment by theotherp** [comment]
Sorry, don't know how that happened

Works with v1.4.6.2. Sorry for the mixup and thanks a lot for the fix!

**Comment by fireshaper** [comment]
Does the comic download without an error now?

**Comment by theotherp** [comment]
See my edit.

**Comment by fireshaper** [comment]
Great! Glad it works now.
