### ISSUE TITLE
No cf_clearance cookie in Chrome or Edge?

### ISSUE THREAD

**Issue by SilentSpartan** [fireshaper/Omnibus#9]
I've tried using Google Chrome and Edge (yikes) to find the cf_clearance cookie but I don't see it. I do see __cfduid though. Did they rename it?

**Comment by fireshaper** [comment]
Yeah, it looks like they removed that cookie. I'm not sure if it was necessary before, I didn't test without it. You should be able to leave it blank and still download some older files. While I was testing this I found a change they made to newer comics so I'm going to post a new release without that cf_clearance cookie and a fix for the other issue.
